version: '3.8'

# This is a sample configuration for running the Novak Trading Engine.
# Users need to create a .env file with their own configuration values.
# Required variables in the .env file:
# - LICENSE_KEY: Your personal license key
# - MT5_SERVER: Your MT5 broker server
# - MT5_LOGIN: Your MT5 account login
# - MT5_PASSWORD: Your MT5 account password
# - CENTRAL_SERVER_URL: URL of the central server (default: https://api.novaktrading.com)
# - MONGODB_URI: MongoDB connection string (optional - can use Docker MongoDB)

services:
  trading-engine:
    image: novak001/novak-trading-engine:latest
    ports:
      - "5001:5001"  # Flask API
    env_file:
      - .env  
    environment:
      - FLASK_APP=src/app.py
      - FLASK_DEBUG=false
      - CENTRAL_SERVER_URL=${CENTRAL_SERVER_URL:-http://147.93.112.143:5002}
      - MONGO_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-secretpassword}
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/novak_trading?authSource=admin
      - SECRET_KEY=${SECRET_KEY:-default_dev_secret_key}
      - LICENSE_KEY=${LICENSE_KEY}
      - MT5_SERVER=${MT5_SERVER}
      - MT5_LOGIN=${MT5_LOGIN}
      - MT5_PASSWORD=${MT5_PASSWORD}
      - MT5_HOST=${MT5_HOST:-localhost}
      - MT5_PORT=${MT5_PORT:-8001}
      - MT5_VNC_USER=${MT5_VNC_USER:-admin}
      - MT5_VNC_PASSWORD=${MT5_VNC_PASSWORD:-admin}
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env 
    restart: unless-stopped
    depends_on:
      - mongodb
      - mt5

  mt5:
    image: novak001/exness-mt5-vnc:latest
    ports:
      - "3001:3000"  # VNC web access (different port than central-server MT5)
      - "8002:8001"  # RPyC server port (different port than central-server MT5)
    environment:
      - CUSTOM_USER=${MT5_VNC_USER:-admin}
      - PASSWORD=${MT5_VNC_PASSWORD:-admin}
    volumes:
      - mt5_data:/config
    restart: unless-stopped

  # Optional local MongoDB - comment out this service if you're using MongoDB Atlas
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-secretpassword}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    
  # MongoDB web-based admin interface
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USERNAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD:-secretpassword}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD:-secretpassword}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-secretpassword}@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
  mt5_data:  # Persist MT5 terminal data 